### ISSUE TITLE
Mod conflict with Reclaim Reuse Recycle

### ISSUE THREAD

**Issue by Stretop** [Vectorial1024/EliteBionicsFramework#1]
When this mod is used with [Reclaim Reuse Recycle](https://github.com/DoctorVanGogh/ReclaimReuseRecycle) - any attempt to use harvesting table gives warning

Elite Bionics Framework has detected some other mod(s) using the vanilla method of BodyPartDef.GetMaxHealth(). While this violation will not cause the game to crash, it will cause those other mod(s) to behave unexpectedly.
Report to Vectorial1024 and the author(s) of those mod(s) to see if those violations can be solved.
   at System.Environment.get_StackTrace()
   at EBF.Patches.Prefix_BodyPart_GetMaxHealth.PreFix(Verse.BodyPartDef __instance, Single __result, Verse.Pawn pawn)
   at Verse.BodyPartDef.GetMaxHealth_Patch1(System.Object , Verse.Pawn )
   at DoctorVanGogh.ReclaimReuseRecycle.Util.HitpointsFactor(Verse.BodyPartRecord part, Verse.HediffSet hediffSet)
   at DoctorVanGogh.ReclaimReuseRecycle.Filter_Corpse+<>c__DisplayClass7_0.<GetReclaimablePartsOrganic>b__1(Verse.Hediff d)
   at System.Linq.Enumerable+<CreateSelectIterator>c__Iterator10`2[[Verse.Hediff, Assembly-CSharp, Version=1.0.7087.21678, Culture=neutral, PublicKeyToken=null],[DoctorVanGogh.ReclaimReuseRecycle.PackedThingDef, ReclaimReuseRecycle, Version=1.5.0.181, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Linq.Enumerable+<CreateWhereIterator>c__Iterator1D`1[[DoctorVanGogh.ReclaimReuseRecycle.PackedThingDef, ReclaimReuseRecycle, Version=1.5.0.181, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Linq.Enumerable.Any(IEnumerable`1 source)
   at DoctorVanGogh.ReclaimReuseRecycle.Filter_Corpse.DoesMatch(Verse.Corpse corpse)
   at DoctorVanGogh.ReclaimReuseRecycle.Filter_Harvested.DoesMatch(Verse.Corpse corpse)
   at DoctorVanGogh.ReclaimReuseRecycle.Filter_Corpse.Matches(Verse.Thing t)
   at DoctorVanGogh.ReclaimReuseRecycle.Filter_Harvested.Matches(Verse.Thing t)
   at Verse.ThingFilter.Allows(Verse.Thing t)
   at RimWorld.Bill.IsFixedOrAllowedIngredient(Verse.Thing thing)
   at RIMMSqol.performance.workgiver_dobill.WorkGiver_DoBill_TryFindBestBillIngredients+<>c__DisplayClass7.<Prefix>b__0(Verse.Thing t)
   at RIMMSqol.performance.workgiver_dobill.WorkGiver_DoBill_TryFindBestBillIngredients+<>c__DisplayClass7.<Prefix>b__5(Verse.Region r)
   at Verse.RegionTraverser+BFSWorker.BreadthFirstTraverseWork(Verse.Region root, Verse.RegionEntryPredicate entryCondition, Verse.RegionProcessor regionProcessor, Int32 maxRegions, RegionType traversableRegionTypes)
   at Verse.RegionTraverser.BreadthFirstTraverse(Verse.Region root, Verse.RegionEntryPredicate entryCondition, Verse.RegionProcessor regionProcessor, Int32 maxRegions, RegionType traversableRegionTypes)
   at RIMMSqol.performance.workgiver_dobill.WorkGiver_DoBill_TryFindBestBillIngredients.Prefix(RimWorld.Bill bill, Verse.Pawn pawn, Verse.Thing billGiver, System.Collections.Generic.List`1 chosen, Boolean ByRef __result)
   at RimWorld.WorkGiver_DoBill.TryFindBestBillIngredients_Patch4(RimWorld.Bill , Verse.Pawn , Verse.Thing , System.Collections.Generic.List`1 )
   at RimWorld.WorkGiver_DoBill.StartOrResumeBillJob(Verse.Pawn pawn, IBillGiver giver)
   at RimWorld.WorkGiver_DoBill.JobOnThing_Patch1(System.Object , Verse.Pawn , Verse.Thing , Boolean )
   at RimWorld.WorkGiver_Scanner.HasJobOnThing(Verse.Pawn pawn, Verse.Thing t, Boolean forced)
   at RimWorld.FloatMenuMakerMap.AddJobGiverWorkOrders_Patch2(IntVec3 , Verse.Pawn , System.Collections.Generic.List`1 , Boolean )
   at RimWorld.FloatMenuMakerMap.AddUndraftedOrders(Vector3 clickPos, Verse.Pawn pawn, System.Collections.Generic.List`1 opts)
   at RimWorld.FloatMenuMakerMap.ChoicesAtFor_Patch2(Vector3 , Verse.Pawn )
   at Verse.FloatMenuMap.DoWindowContents(Rect inRect)
   at Verse.Window+<WindowOnGUI>c__AnonStorey0.<>m__0(Int32 x)
   at UnityEngine.GUI.CallWindowDelegate(UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)

As a result - all corpses are considered as not having harvestable parts, even when they have implants and 100% part's HP.

**Comment by Vectorial1024** [comment]
Quick question, did you obtain this mod from GitHub or Steam?

I feel like this has to do with a bug that I fixed a while ago involving the 0 max health and the related calculation errors, and I think I didnt update the GitHub version back then.

**Comment by Stretop** [comment]
From GitHub. It shows version 1.0.0.7.

**Comment by Vectorial1024** [comment]
Welp.

Local latest (and should also be Steam latest) version is v1.0.4... That version already fixed the 0 max health bug.

My dumbass decided not to update the Github version...

Still, lemme quickly review the code and pack EBF to make a release here.

**Comment by Vectorial1024** [comment]
Update: I have packed the mod (v1.0.4) and put it at the Releases section of the Code tab.

Check if the bug and warning still persists.

**Comment by Stretop** [comment]
Done some testing - works fine so far. Closing this issue for now.
